### ISSUE TITLE
Add registration page

### ISSUE THREAD

**Issue by gurland** [gurland/SIGame_web#1]
Create templates and views to serve on '/' route which should be used for user registration and/or login.

**Comment by gurland** [comment]
Template is ready to use. Login and Register are in single page.
<details>
  <summary>Screenshots</summary>
 

![image](https://user-images.githubusercontent.com/30530987/41370705-01a0b274-6f51-11e8-9661-8d384ab77954.png)
![image](https://user-images.githubusercontent.com/30530987/41370716-0968339c-6f51-11e8-98ab-3c78a09197ff.png)
</details>

Now we have to make backend functionality in that way:

1. Redirect unauthorized users from `/` to `/authentication`
2. Make model for user in peewee
3. Validate data from forms, create views for '/login' and '/register' with `POST` method. Those views will save and check user's credentials and redirect to pages in cases of unsuccessful login/register
4. Add csrf token validation

**Comment by gurland** [comment]
#b227a8165fd90f684b2f71fede4b02d84505fc83

**Comment by gurland** [comment]
#15

**Comment by gurland** [comment]
#1

**Comment by dvoyakiy** [comment]
Created views for '/login' and '/register' with appropriate functionality
e21eee6cfd6f640a2ed6f8636cceb0987452a54e
7339b8ea992eebcbff9150fe2b92ae5b38fac0d0
9e524580252d1ffd26fb1beb15d45e47898de5fc
9f96c13792b51833e4cca2b858ff13f79129d524
9466df6d21ba278305ee81a78a05fabf184ba944
e95686063f11811f11004c2d01cc3631bf6fbbf3

**Comment by dvoyakiy** [comment]
Created user model in peewee
728560e284a20acebcf0f66a4d1528acd954c6ba

**Comment by kotoshii** [comment]
Created user model in peewee 728560e284a20acebcf0f66a4d1528acd954c6ba

**Comment by kotoshii** [comment]
Created views for '/login' and '/register' with appropriate functionality 
e21eee6cfd6f640a2ed6f8636cceb0987452a54e 
7339b8ea992eebcbff9150fe2b92ae5b38fac0d0 
9e524580252d1ffd26fb1beb15d45e47898de5fc 
9f96c13792b51833e4cca2b858ff13f79129d524 
9466df6d21ba278305ee81a78a05fabf184ba944 
e95686063f11811f11004c2d01cc3631bf6fbbf3

**Comment by kotoshii** [comment]
Added redirect for unauthorized users from '/' to '/authentication'
2b073d36fd615ef6eefccc38946530cb18a91150

**Comment by gurland** [comment]
Add password hashing support
15ed86a70553c9450b11721cd4bf88363b88e143
cc2d60316544575c6009b6eeee960cd655fcb607

**Comment by gurland** [comment]
TODO: http://flask-login.readthedocs.io/en/latest/#login-example 
```You MUST validate the value of the next parameter. If you do not, your application will be vulnerable to open redirects. For an example implementation of is_safe_url see this Flask Snippet.``` [Snippet](http://flask.pocoo.org/snippets/62/)
Fix open redirect vulnerability

**Comment by gurland** [comment]
https://github.com/gurland/SIGame_web/pull/2
