### ISSUE TITLE
Refactor auth.html template

### ISSUE THREAD

**Issue by gurland** [gurland/SIGame_web#15]
- Start using flex boxes instead of hardcoded things like register/login buttons

**Comment by kotoshii** [comment]
Done
![image](https://user-images.githubusercontent.com/40234487/42712557-c70f957e-86f4-11e8-9bd0-9ddfc0de2119.png)
![image](https://user-images.githubusercontent.com/40234487/42712619-f41b1c46-86f4-11e8-93a9-786d3dda1ae5.png)
