### ISSUE TITLE
Rebuild front-end using ReactJS

### ISSUE THREAD

**Issue by kotoshii** [gurland/SIGame_web#26]
- Create approximate patterns for components.
- Build components.

**Comment by kotoshii** [comment]
Made auth page
![default](https://user-images.githubusercontent.com/40234487/46955324-563ac300-d09b-11e8-8d77-0101fb88c072.png)

**Comment by kotoshii** [comment]
Made lobby page
![default](https://user-images.githubusercontent.com/40234487/48304921-dd5c4900-e52a-11e8-8faf-8750c3d98060.png)
![default](https://user-images.githubusercontent.com/40234487/48304923-e8af7480-e52a-11e8-96d8-2c03904def79.png)
![default](https://user-images.githubusercontent.com/40234487/48304938-1a284000-e52b-11e8-86df-765c276c6df7.png)

**Comment by gurland** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Client build system](https://trello.com/c/zx7fq1ws/1-client-build-system)

**Comment by gurland** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Move upload pack button](https://trello.com/c/ONEFwmsE/4-move-upload-pack-button)

**Comment by gurland** [comment]
#27
